version: '2'

################################################
# adjacents docker-compose file for cassandra + python
# updated May 2018
# author: Valerie Parham-Thompson

services:

################################################
# application server
    app:
        container_name: app
        image: dataindataout/cassandra-python
        hostname: app
        networks:
          myring:
            ipv4_address: 172.16.238.10
        command: tail -f /dev/null

################################################
# servers to run a Cassandra cluster on
# the "CASSANDRA*" variables will get pulled in via docker-entrypoint.sh

    DC1C1:
        container_name: DC1C1
        image: cassandra:latest
        hostname: DC1C1
        networks: 
            - myring
        volumes:
            - ./n1data:/var/lib/cassandra
            - ./configuration/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
        ports:
          - "127.0.0.1:7401:7400"
        environment:
            - CASSANDRA_SEEDS=DC1C1,DC1C2
            - CASSANDRA_CLUSTER_NAME=Dev_Cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC1
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        command: bash -c 'sleep 10;  /docker-entrypoint.sh cassandra -f'

    DC1C2:
        container_name: DC1C2
        image: cassandra:latest
        hostname: DC1C2
        networks:
            - myring
        volumes:
            - ./n2data:/var/lib/cassandra
            - ./configuration/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
        ports:
          - "127.0.0.1:7402:7400"
        environment:
            - CASSANDRA_SEEDS=DC1C1,DC1C2,DC2C1,DC2C2
            - CASSANDRA_CLUSTER_NAME=Dev_Cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC2
        depends_on:
              - DC1C1
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        command: bash -c 'sleep 10;  /docker-entrypoint.sh cassandra -f'

    DC1C3:
        container_name: DC1C3
        image: cassandra:latest
        hostname: DC1C3
        networks: 
            - myring
        volumes:
            - ./n3data:/var/lib/cassandra
            - ./configuration/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
        ports:
          - "127.0.0.1:7403:7400"
        environment:
            - CASSANDRA_SEEDS=DC1C1,DC1C2,DC2C1,DC2C2
            - CASSANDRA_CLUSTER_NAME=Dev_Cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC3
        depends_on:
              - DC1C1
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        command: bash -c 'sleep 10;  /docker-entrypoint.sh cassandra -f'

########################################################
# network

networks:
    myring:    
        driver: bridge
        ipam:
          driver: default
          config:
          - subnet: 172.16.238.0/24
